---
title: "Data Import"
output: github_document
---

This is for doig data import
```{r}
library(tidyverse)
library(readxl)
library(haven)
```


Import our first dataset

```{r}
litters_df=
  read_csv(
    file = "data/data_import_examples/FAS_litters.csv",
    na = c("","NA" , "." )
  )

litters_df = janitor::clean_names(litters_df)
```
import ur second data

把什么变成加好？？



```{r}
pups_df=
  read_csv("data/data_import_examples/FAS_pups.csv", 
           skip = 3,
           na = c("","NA",".")
  )

pups_df =janitor::clean_names(pups_df)
```
## Look the data
```{r}

litters_df
pups_df
```

Head or tail 

```{r}
head(litters_df, 20)

tail(pups_df, 5)
```

Skimming??

```{r}
skimr::skim(pups_df)
```

## 0h execel

Jenny Brayan made  `readxl` to solve our problems.

```{r}
mlb_df=
  read_excel("data/data_import_examples/mlb11.xlsx")

```


look at the data
```{r}
mlb_df
```

Load
Import   FORT words

```{r}
fotr_df = 
  read_excel(
    "data/data_import_examples/LotR_Words.xlsx",
    range = "B3:D6"
  )
```
## Import SAS 
Read in thr PULSE dataset

```{r}

pulse_df = 
  read_sas("data/data_import_examples/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```

## What's so bad about `read.csv()`

Import pups with `read.csv()`

```{r}
pups_df_base = 
  read.csv("data/data_import_examples/FAS_pups.csv")

pups_df_base
```

Won't show: lazy about variables names; super slow for big dataset.
